### ISSUE TITLE
Write a zcash-rpc ingestor

### ISSUE THREAD

**Issue by gtank** [zcash-hackworks/lightwalletd#11]
This will let you spin up a light wallet without having to zmq the whole chain. It will also allow filling in gaps in a database, and generally provide some fallback options for everything. The implied json-rpc support will dovetail with #12.

Check the license situation, but the btcjson submodule of https://github.com/btcsuite/btcd looks promising.

**Comment by gtank** [comment]
The btcd APIs are fairly specific to Bitcoin. Using those libraries may still save time but it probably isn't the right answer long-term.

**Comment by gtank** [comment]
My current favored approach to this is composition between zcash-cli and https://github.com/gtank/zmqpipe, rather than teaching the server about the RPC calls.

**Comment by mdr0id** [comment]
Note: #43 should resolve this. Will close when it hits master.
