### ISSUE TITLE
Add SemVer to lightwalletd

### ISSUE THREAD

**Issue by braddmiller** [zcash-hackworks/lightwalletd#130]
As a wallet developer, I would like to be able to refer to specific versions of the lightwalletd software and have control over upgrading when new features are released.

Criteria:
1) The first release of lightwalletd using the Sem Ver policy is tagged and pushed

**Comment by LarryRuane** [comment]
Merged PR https://github.com/zcash-hackworks/lightwalletd/pull/139, which adds a `-version` argument to the two executables (`ingest` and `server`) so users can discover which version they're running. Currently:
```
$ go run cmd/ingest/main.go -version
lightwalletd ingest version v0.1.0
```
Now all that needs to be done is tag current master, which @mdr0id will do. We'll have to remember to update this string in the source code when we tag a new version.
