### ISSUE TITLE
add GetLightdInfo RPC

### ISSUE THREAD

**Issue by LarryRuane** [zcash-hackworks/lightwalletd#141]
Returns chain info such as version, chain (main or test), height, Vendor, t-addr support flag, Sapling activation height, branchID. I'm not sure if our wallet engineers will find this useful, but there's no harm in merging it (it's a small amount of code), and ZECWallet definitely needs it. See #137.

**Comment by braddmiller** [comment]
If vendor and version are not necessary as a return from this RPC, they should be removed
