### ISSUE TITLE
Lightwalletd does not recover from failed launch (Upstream)

### ISSUE THREAD

**Issue by braddmiller** [zcash-hackworks/lightwalletd#150]
There was an issue discovered in Aditya's fork of lightwalletd, including here so we can resolve this if we run into the problem while merging in the changes from that repo.

https://github.com/adityapk00/lightwalletd/issues/3

**Comment by LarryRuane** [comment]
This will be fixed by https://github.com/zcash-hackworks/lightwalletd/pull/149.
