### ISSUE TITLE
Internal-Security Finding #2: Unit Test Functions in bytestring.go

### ISSUE THREAD

**Issue by defuse** [zcash-hackworks/lightwalletd#28]
The lowest-level parsing functions in `bytestring.go` don't have unit tests. There is at least one bug in them: on platforms where `int` is 32 bits, [ReadCompactSize](https://github.com/zcash-hackworks/lightwalletd/blob/master/parser/internal/bytestring/bytestring.go#L82)'s `length` can overflow and an incorrect result will be returned.

Close this by adding unit tests for the the functions in `bytestring.go`. Also see #29 about setting up automated CI testing.

**Comment by gtank** [comment]
Yeah, we found that bug with fuzzing last year. It's prevented in practice by all the validation zcashd already does, but if you were to run this parser on block data sourced elsewhere it might be a concern. Worth fixing and testing, but not an extremely high priority.

**Comment by LarryRuane** [comment]
Closing, fixed by #73

**Comment by mdr0id** [comment]
Closing due to above PR
