### ISSUE TITLE
Don't use block height as a primary key

### ISSUE THREAD

**Issue by gtank** [zcash-hackworks/lightwalletd#32]
It's likely causing failures during reorgs or other transient failures that result in a rebroadcast. Found by @ianamunoz and @gmale.

https://github.com/zcash-hackworks/lightwalletd/blob/master/storage/sqlite3.go#L30

**Comment by gmale** [comment]
This basically boils down to "implement re-orgs" which is a feature we knowingly punted on, as a trade-off.

**Comment by gmale** [comment]
Related to and possibly a duplicate of #31

**Comment by mms710** [comment]
Relates to https://github.com/zcash/zcash-android-wallet-sdk/issues/23

**Comment by mdr0id** [comment]
No longer relevant due to updates to mentioned topics
