### ISSUE TITLE
Zcashd going down crashes Ingestor

### ISSUE THREAD

**Issue by gmale** [zcash-hackworks/lightwalletd#45]
The ingestor crashes when Zcashd goes down (via Ctrl+C for example) with the following error

> FATAL[2019-06-08T03:15:57-04:00] error with getblock                           app=zmqclient error="error requesting block: Post http://127.0.0.1:8232: dial tcp 127.0.0.1:8232: connect: connection refused" height=511887
exit status 1

This might make the ingestor more brittle than it needs to be. Probably should warn rather than crash and periodically check for zcashd to return.

**Comment by mdr0id** [comment]
I believe this was a case handled in the remove_0mq patch. I just tested on a local node to confirm:

```
6553395e2c3d64328d02c6322b0e803887 block_height=280389 block_version=4 error="<nil>" prev_hash=000917255e61ed87019d60c3475054a648e8eb41f5ca31d57b6e3fc0d86e49be sapling=false tx_count=1
WARNING[2019-09-23T14:42:33-07:00] error with getblock                           app=lightwalletd error="error requesting block: Post http://127.0.0.1:18232: EOF" height=280390
WARNING[2019-09-23T14:43:33-07:00] error with getblock                           app=lightwalletd error="error requesting block: Post http://127.0.0.1:18232: dial tcp 127.0.0.1:18232: connect: connection refused" height=280390
WARNING[2019-09-23T14:44:33-07:00] error with getblock                           app=lightwalletd error="error requesting block: Post http://127.0.0.1:18232: dial tcp 127.0.0.1:18232: connect: connection refused" height=280390
WARNING[2019-09-23T14:44:33-07:00] unable to issue RPC call to zcashd node 3 times  app=lightwalletd timeouts=3
```

Please reopen if the issue exists
